version: '3'

services:
  # Kafka 서비스
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - talk-platform-net

  # Redis 데이터베이스 서비스 (데이터 저장)
  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - talk-platform-net

  # MySQL 데이터베이스 서비스 (로그 저장)
  mysql:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 8282
      MYSQL_DATABASE: talkConcert
      MYSQL_USER: user
      MYSQL_PASSWORD: 8282
    networks:
      - talk-platform-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    depends_on:
        - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2

    networks:
      - talk-platform-net

networks:
  talk-platform-net:
    driver: bridge
